CREATE TABLE IF NOT EXISTS `MindTable` (
  `mindID` int(11) NOT NULL AUTO_INCREMENT,
  `mindIDAlias` varchar(100) NOT NULL,
  `parentId` int(11) NOT NULL,
  `userID` int(11) NOT NULL,
  `nodeId` int(11) NOT NULL,
  `mindTitle` varchar(50) NOT NULL,
  `createdDates` datetime NOT NULL,
  `modifiedDates` datetime NOT NULL,
  `dimendionsX` int(11) NOT NULL,
  `dimendionsY` int(11) NOT NULL,
  `autosave` varchar(50) NOT NULL,
  `caption` varchar(50) NOT NULL,
  `style` varchar(50) NOT NULL DEFAULT 'normal',
  `weight` varchar(50) NOT NULL DEFAULT 'normal',
  `decoration` varchar(50) NOT NULL DEFAULT 'none',
  `size` int(11) NOT NULL DEFAULT '20',
  `textColor` varchar(50) NOT NULL DEFAULT '#000000',
  `offsetX` int(11) NOT NULL,
  `offsetY` int(11) NOT NULL,
  `foldChildren` varchar(50) NOT NULL DEFAULT 'false',
  `branchColor` varchar(50) NOT NULL DEFAULT '#000000',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mindID`),
  UNIQUE KEY `mindID` (`mindID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=600;